using System.Diagnostics;
using Unity.Collections;
using UnityEngine;

/// <summary>
/// Use ints instead of bytes.
/// </summary>
public class SoATest3 : MonoBehaviour {
    const int entityCount = 50_000;

    enum State : byte {
        A, B, C, D, E, F, G, H, I, J, K, L, M,
        N, O, P, Q, R, S, T, U, V, W, X, Y, Z
    }

    NativeArray<byte> a;
    NativeArray<int> b;
    NativeArray<int> c;
    NativeArray<int> d;
    NativeArray<int> e;
    NativeArray<int> f;
    NativeArray<int> g;
    NativeArray<int> h;
    NativeArray<int> i;
    NativeArray<int> j;
    NativeArray<int> k;
    NativeArray<int> l;
    NativeArray<int> m;
    NativeArray<int> n;
    NativeArray<int> o;
    NativeArray<int> p;
    NativeArray<int> q;
    NativeArray<int> r;
    NativeArray<int> s;
    NativeArray<int> t;
    NativeArray<int> u;
    NativeArray<int> v;
    NativeArray<int> w;
    NativeArray<int> x;
    NativeArray<int> y;
    NativeArray<int> z;
    NativeArray<int> aa;
    NativeArray<int> ab;
    NativeArray<int> ac;
    NativeArray<int> ad;
    NativeArray<int> ae;
    NativeArray<int> af;
    NativeArray<int> ag;
    NativeArray<int> ah;
    NativeArray<int> ai;
    NativeArray<int> aj;
    NativeArray<int> ak;
    NativeArray<int> al;
    NativeArray<int> am;
    NativeArray<int> an;
    NativeArray<int> ao;
    NativeArray<int> ap;
    NativeArray<int> aq;
    NativeArray<int> ar;
    NativeArray<int> @as;
    NativeArray<int> at;
    NativeArray<int> au;
    NativeArray<int> av;
    NativeArray<int> aw;
    NativeArray<int> ax;
    NativeArray<int> ay;
    NativeArray<int> az;
    NativeArray<int> ba;
    NativeArray<int> bb;
    NativeArray<int> bc;
    NativeArray<int> bd;
    NativeArray<int> be;
    NativeArray<int> bf;
    NativeArray<int> bg;
    NativeArray<int> bh;
    NativeArray<int> bi;
    NativeArray<int> bj;
    NativeArray<int> bk;
    NativeArray<int> bl;
    NativeArray<int> bm;
    NativeArray<int> bn;
    NativeArray<int> bo;
    NativeArray<int> bp;
    NativeArray<int> bq;
    NativeArray<int> br;
    NativeArray<int> bs;
    NativeArray<int> bt;
    NativeArray<int> bu;
    NativeArray<int> bv;
    NativeArray<int> bw;
    NativeArray<int> bx;
    NativeArray<int> by;
    NativeArray<int> bz;
    NativeArray<int> ca;
    NativeArray<int> cb;
    NativeArray<int> cc;
    NativeArray<int> cd;
    NativeArray<int> ce;
    NativeArray<int> cf;
    NativeArray<int> cg;
    NativeArray<int> ch;
    NativeArray<int> ci;
    NativeArray<int> cj;
    NativeArray<int> ck;
    NativeArray<int> cl;
    NativeArray<int> cm;
    NativeArray<int> cn;
    NativeArray<int> co;
    NativeArray<int> cp;
    NativeArray<int> cq;
    NativeArray<int> cr;
    NativeArray<int> cs;
    NativeArray<int> ct;
    NativeArray<int> cu;
    NativeArray<int> cv;
    NativeArray<int> cw;
    NativeArray<int> cx;
    NativeArray<int> cy;
    NativeArray<int> cz;
    NativeArray<int> da;
    NativeArray<int> db;
    NativeArray<int> dc;
    NativeArray<int> dd;
    NativeArray<int> de;
    NativeArray<int> df;
    NativeArray<int> dg;
    NativeArray<int> dh;
    NativeArray<int> di;
    NativeArray<int> dj;
    NativeArray<int> dk;
    NativeArray<int> dl;
    NativeArray<int> dm;
    NativeArray<int> dn;
    NativeArray<int> doo;
    NativeArray<int> dp;
    NativeArray<int> dq;
    NativeArray<int> dr;
    NativeArray<int> ds;
    NativeArray<int> dt;
    NativeArray<int> du;
    NativeArray<int> dv;
    NativeArray<int> dw;
    NativeArray<int> dx;
    NativeArray<int> dy;
    NativeArray<int> dz;
    NativeArray<int> ea;
    NativeArray<int> eb;
    NativeArray<int> ec;
    NativeArray<int> ed;
    NativeArray<int> ee;
    NativeArray<int> ef;
    NativeArray<int> eg;
    NativeArray<int> eh;
    NativeArray<int> ei;
    NativeArray<int> ej;
    NativeArray<int> ek;
    NativeArray<int> el;
    NativeArray<int> em;
    NativeArray<int> en;
    NativeArray<int> eo;
    NativeArray<int> ep;
    NativeArray<int> eq;
    NativeArray<int> er;
    NativeArray<int> es;
    NativeArray<int> et;
    NativeArray<int> eu;
    NativeArray<int> ev;
    NativeArray<int> ew;
    NativeArray<int> ex;
    NativeArray<int> ey;
    NativeArray<int> ez;
    NativeArray<int> fa;
    NativeArray<int> fb;
    NativeArray<int> fc;
    NativeArray<int> fd;
    NativeArray<int> fe;
    NativeArray<int> ff;
    NativeArray<int> fg;
    NativeArray<int> fh;
    NativeArray<int> fi;
    NativeArray<int> fj;
    NativeArray<int> fk;
    NativeArray<int> fl;
    NativeArray<int> fm;
    NativeArray<int> fn;
    NativeArray<int> fo;
    NativeArray<int> fp;
    NativeArray<int> fq;
    NativeArray<int> fr;
    NativeArray<int> fs;
    NativeArray<int> ft;
    NativeArray<int> fu;
    NativeArray<int> fv;
    NativeArray<int> fw;
    NativeArray<int> fx;
    NativeArray<int> fy;
    NativeArray<int> fz;
    NativeArray<int> ga;
    NativeArray<int> gb;
    NativeArray<int> gc;
    NativeArray<int> gd;
    NativeArray<int> ge;
    NativeArray<int> gf;
    NativeArray<int> gg;
    NativeArray<int> gh;
    NativeArray<int> gi;
    NativeArray<int> gj;
    NativeArray<int> gk;
    NativeArray<int> gl;

    Stopwatch stopwatch = new Stopwatch();

    void Start() {
        a = new NativeArray<byte>(entityCount, Allocator.Persistent);
        b = NewArray();
        c = NewArray();
        d = NewArray();
        e = NewArray();
        f = NewArray();
        g = NewArray();
        h = NewArray();
        i = NewArray();
        j = NewArray();
        k = NewArray();
        l = NewArray();
        m = NewArray();
        n = NewArray();
        o = NewArray();
        p = NewArray();
        q = NewArray();
        r = NewArray();
        s = NewArray();
        t = NewArray();
        u = NewArray();
        v = NewArray();
        w = NewArray();
        x = NewArray();
        y = NewArray();
        z = NewArray();
        aa = NewArray();
        ab = NewArray();
        ac = NewArray();
        ad = NewArray();
        ae = NewArray();
        af = NewArray();
        ag = NewArray();
        ah = NewArray();
        ai = NewArray();
        aj = NewArray();
        ak = NewArray();
        al = NewArray();
        am = NewArray();
        an = NewArray();
        ao = NewArray();
        ap = NewArray();
        aq = NewArray();
        ar = NewArray();
        @as = NewArray();
        at = NewArray();
        au = NewArray();
        av = NewArray();
        aw = NewArray();
        ax = NewArray();
        ay = NewArray();
        az = NewArray();
        ba = NewArray();
        bb = NewArray();
        bc = NewArray();
        bd = NewArray();
        be = NewArray();
        bf = NewArray();
        bg = NewArray();
        bh = NewArray();
        bi = NewArray();
        bj = NewArray();
        bk = NewArray();
        bl = NewArray();
        bm = NewArray();
        bn = NewArray();
        bo = NewArray();
        bp = NewArray();
        bq = NewArray();
        br = NewArray();
        bs = NewArray();
        bt = NewArray();
        bu = NewArray();
        bv = NewArray();
        bw = NewArray();
        bx = NewArray();
        by = NewArray();
        bz = NewArray();
        ca = NewArray();
        cb = NewArray();
        cc = NewArray();
        cd = NewArray();
        ce = NewArray();
        cf = NewArray();
        cg = NewArray();
        ch = NewArray();
        ci = NewArray();
        cj = NewArray();
        ck = NewArray();
        cl = NewArray();
        cm = NewArray();
        cn = NewArray();
        co = NewArray();
        cp = NewArray();
        cq = NewArray();
        cr = NewArray();
        cs = NewArray();
        ct = NewArray();
        cu = NewArray();
        cv = NewArray();
        cw = NewArray();
        cx = NewArray();
        cy = NewArray();
        cz = NewArray();
        da = NewArray();
        db = NewArray();
        dc = NewArray();
        dd = NewArray();
        de = NewArray();
        df = NewArray();
        dg = NewArray();
        dh = NewArray();
        di = NewArray();
        dj = NewArray();
        dk = NewArray();
        dl = NewArray();
        dm = NewArray();
        dn = NewArray();
        doo = NewArray();
        dp = NewArray();
        dq = NewArray();
        dr = NewArray();
        ds = NewArray();
        dt = NewArray();
        du = NewArray();
        dv = NewArray();
        dw = NewArray();
        dx = NewArray();
        dy = NewArray();
        dz = NewArray();
        ea = NewArray();
        eb = NewArray();
        ec = NewArray();
        ed = NewArray();
        ee = NewArray();
        ef = NewArray();
        eg = NewArray();
        eh = NewArray();
        ei = NewArray();
        ej = NewArray();
        ek = NewArray();
        el = NewArray();
        em = NewArray();
        en = NewArray();
        eo = NewArray();
        ep = NewArray();
        eq = NewArray();
        er = NewArray();
        es = NewArray();
        et = NewArray();
        eu = NewArray();
        ev = NewArray();
        ew = NewArray();
        ex = NewArray();
        ey = NewArray();
        ez = NewArray();
        fa = NewArray();
        fb = NewArray();
        fc = NewArray();
        fd = NewArray();
        fe = NewArray();
        ff = NewArray();
        fg = NewArray();
        fh = NewArray();
        fi = NewArray();
        fj = NewArray();
        fk = NewArray();
        fl = NewArray();
        fm = NewArray();
        fn = NewArray();
        fo = NewArray();
        fp = NewArray();
        fq = NewArray();
        fr = NewArray();
        fs = NewArray();
        ft = NewArray();
        fu = NewArray();
        fv = NewArray();
        fw = NewArray();
        fx = NewArray();
        fy = NewArray();
        fz = NewArray();
        ga = NewArray();
        gb = NewArray();
        gc = NewArray();
        gd = NewArray();
        ge = NewArray();
        gf = NewArray();
        gg = NewArray();
        gh = NewArray();
        gi = NewArray();
        gj = NewArray();
        gk = NewArray();
        gl = NewArray();
        for (int i = 0; i < entityCount; i++)
            a[i] = (byte)State.A;
    }

    NativeArray<int> NewArray() {
        return new NativeArray<int>(
            entityCount,
            Allocator.Persistent);
    }

    void Update() {
        stopwatch.Restart();
        for (int ii = 0; ii < entityCount; ii++) {
            switch ((State)a[ii]) {
                case State.A:
                    b[ii]++;
                    co[ii]++;
                    gl[ii]++;
                    break;
                case State.B:
                    d[ii]++;
                    bq[ii]++;
                    ee[ii]++;
                    break;
                case State.C:
                    g[ii]++;
                    bs[ii]++;
                    eg[ii]++;
                    break;
                case State.D:
                    j[ii]++;
                    bu[ii]++;
                    ej[ii]++;
                    break;
                case State.E:
                    m[ii]++;
                    bw[ii]++;
                    el[ii]++;
                    break;
                case State.F:
                    p[ii]++;
                    by[ii]++;
                    en[ii]++;
                    break;
                case State.G:
                    s[ii]++;
                    ca[ii]++;
                    ep[ii]++;
                    break;
                case State.H:
                    v[ii]++;
                    cc[ii]++;
                    er[ii]++;
                    break;
                case State.I:
                    y[ii]++;
                    ce[ii]++;
                    et[ii]++;
                    break;
                case State.J:
                    ab[ii]++;
                    cg[ii]++;
                    ev[ii]++;
                    break;
                case State.K:
                    ad[ii]++;
                    ci[ii]++;
                    ex[ii]++;
                    break;
                case State.L:
                    ag[ii]++;
                    ck[ii]++;
                    ez[ii]++;
                    break;
                case State.M:
                    aj[ii]++;
                    cm[ii]++;
                    fb[ii]++;
                    break;
                case State.N:
                    al[ii]++;
                    co[ii]++;
                    fd[ii]++;
                    break;
                case State.O:
                    ao[ii]++;
                    cq[ii]++;
                    ff[ii]++;
                    break;
                case State.P:
                    ar[ii]++;
                    cs[ii]++;
                    fh[ii]++;
                    break;
                case State.Q:
                    at[ii]++;
                    cu[ii]++;
                    fj[ii]++;
                    break;
                case State.R:
                    aw[ii]++;
                    cw[ii]++;
                    fl[ii]++;
                    break;
                case State.S:
                    az[ii]++;
                    cy[ii]++;
                    fn[ii]++;
                    break;
                case State.T:
                    bb[ii]++;
                    da[ii]++;
                    fp[ii]++;
                    break;
                case State.U:
                    be[ii]++;
                    dc[ii]++;
                    fr[ii]++;
                    break;
                case State.V:
                    bg[ii]++;
                    de[ii]++;
                    ft[ii]++;
                    break;
                case State.W:
                    bj[ii]++;
                    dg[ii]++;
                    fv[ii]++;
                    break;
                case State.X:
                    bl[ii]++;
                    di[ii]++;
                    fx[ii]++;
                    break;
                case State.Y:
                    bn[ii]++;
                    dk[ii]++;
                    fz[ii]++;
                    break;
                case State.Z:
                    bq[ii]++;
                    dm[ii]++;
                    gl[ii]++;
                    break;
            }
        }
        stopwatch.Stop();
        UnityEngine.Debug.Log($"SoA Update: {stopwatch.Elapsed.TotalMilliseconds:F4} ms");
    }

    void OnDestroy() {
        Dispose(ref a);
        Dispose(ref b);
        Dispose(ref c);
        Dispose(ref d);
        Dispose(ref e);
        Dispose(ref f);
        Dispose(ref g);
        Dispose(ref h);
        Dispose(ref i);
        Dispose(ref j);
        Dispose(ref k);
        Dispose(ref l);
        Dispose(ref m);
        Dispose(ref n);
        Dispose(ref o);
        Dispose(ref p);
        Dispose(ref q);
        Dispose(ref r);
        Dispose(ref s);
        Dispose(ref t);
        Dispose(ref u);
        Dispose(ref v);
        Dispose(ref w);
        Dispose(ref x);
        Dispose(ref y);
        Dispose(ref z);
        Dispose(ref aa);
        Dispose(ref ab);
        Dispose(ref ac);
        Dispose(ref ad);
        Dispose(ref ae);
        Dispose(ref af);
        Dispose(ref ag);
        Dispose(ref ah);
        Dispose(ref ai);
        Dispose(ref aj);
        Dispose(ref ak);
        Dispose(ref al);
        Dispose(ref am);
        Dispose(ref an);
        Dispose(ref ao);
        Dispose(ref ap);
        Dispose(ref aq);
        Dispose(ref ar);
        Dispose(ref @as);
        Dispose(ref at);
        Dispose(ref au);
        Dispose(ref av);
        Dispose(ref aw);
        Dispose(ref ax);
        Dispose(ref ay);
        Dispose(ref az);
        Dispose(ref ba);
        Dispose(ref bb);
        Dispose(ref bc);
        Dispose(ref bd);
        Dispose(ref be);
        Dispose(ref bf);
        Dispose(ref bg);
        Dispose(ref bh);
        Dispose(ref bi);
        Dispose(ref bj);
        Dispose(ref bk);
        Dispose(ref bl);
        Dispose(ref bm);
        Dispose(ref bn);
        Dispose(ref bo);
        Dispose(ref bp);
        Dispose(ref bq);
        Dispose(ref br);
        Dispose(ref bs);
        Dispose(ref bt);
        Dispose(ref bu);
        Dispose(ref bv);
        Dispose(ref bw);
        Dispose(ref bx);
        Dispose(ref by);
        Dispose(ref bz);
        Dispose(ref ca);
        Dispose(ref cb);
        Dispose(ref cc);
        Dispose(ref cd);
        Dispose(ref ce);
        Dispose(ref cf);
        Dispose(ref cg);
        Dispose(ref ch);
        Dispose(ref ci);
        Dispose(ref cj);
        Dispose(ref ck);
        Dispose(ref cl);
        Dispose(ref cm);
        Dispose(ref cn);
        Dispose(ref co);
        Dispose(ref cp);
        Dispose(ref cq);
        Dispose(ref cr);
        Dispose(ref cs);
        Dispose(ref ct);
        Dispose(ref cu);
        Dispose(ref cv);
        Dispose(ref cw);
        Dispose(ref cx);
        Dispose(ref cy);
        Dispose(ref cz);
        Dispose(ref da);
        Dispose(ref db);
        Dispose(ref dc);
        Dispose(ref dd);
        Dispose(ref de);
        Dispose(ref df);
        Dispose(ref dg);
        Dispose(ref dh);
        Dispose(ref di);
        Dispose(ref dj);
        Dispose(ref dk);
        Dispose(ref dl);
        Dispose(ref dm);
        Dispose(ref dn);
        Dispose(ref doo);
        Dispose(ref dp);
        Dispose(ref dq);
        Dispose(ref dr);
        Dispose(ref ds);
        Dispose(ref dt);
        Dispose(ref du);
        Dispose(ref dv);
        Dispose(ref dw);
        Dispose(ref dx);
        Dispose(ref dy);
        Dispose(ref dz);
        Dispose(ref ea);
        Dispose(ref eb);
        Dispose(ref ec);
        Dispose(ref ed);
        Dispose(ref ee);
        Dispose(ref ef);
        Dispose(ref eg);
        Dispose(ref eh);
        Dispose(ref ei);
        Dispose(ref ej);
        Dispose(ref ek);
        Dispose(ref el);
        Dispose(ref em);
        Dispose(ref en);
        Dispose(ref eo);
        Dispose(ref ep);
        Dispose(ref eq);
        Dispose(ref er);
        Dispose(ref es);
        Dispose(ref et);
        Dispose(ref eu);
        Dispose(ref ev);
        Dispose(ref ew);
        Dispose(ref ex);
        Dispose(ref ey);
        Dispose(ref ez);
        Dispose(ref fa);
        Dispose(ref fb);
        Dispose(ref fc);
        Dispose(ref fd);
        Dispose(ref fe);
        Dispose(ref ff);
        Dispose(ref fg);
        Dispose(ref fh);
        Dispose(ref fi);
        Dispose(ref fj);
        Dispose(ref fk);
        Dispose(ref fl);
        Dispose(ref fm);
        Dispose(ref fn);
        Dispose(ref fo);
        Dispose(ref fp);
        Dispose(ref fq);
        Dispose(ref fr);
        Dispose(ref fs);
        Dispose(ref ft);
        Dispose(ref fu);
        Dispose(ref fv);
        Dispose(ref fw);
        Dispose(ref fx);
        Dispose(ref fy);
        Dispose(ref fz);
        Dispose(ref ga);
        Dispose(ref gb);
        Dispose(ref gc);
        Dispose(ref gd);
        Dispose(ref ge);
        Dispose(ref gf);
        Dispose(ref gg);
        Dispose(ref gh);
        Dispose(ref gi);
        Dispose(ref gj);
        Dispose(ref gk);
        Dispose(ref gl);
    }

    static void Dispose(ref NativeArray<byte> array) {
        if (array.IsCreated)
            array.Dispose();
    }

    static void Dispose(ref NativeArray<int> array) {
        if (array.IsCreated)
            array.Dispose();
    }
}