using System.Diagnostics;
using Unity.Collections;
using UnityEngine;

/// <summary>
/// Instead of randomizing state, set all entities to State.A.
/// </summary>
public class SoATest2 : MonoBehaviour{
    const int entityCount = 50_000;

    enum State : byte {
        A, B, C, D, E, F, G, H, I, J, K, L, M,
        N, O, P, Q, R, S, T, U, V, W, X, Y, Z
    }

    NativeArray<byte> a;
    NativeArray<byte> b;
    NativeArray<byte> c;
    NativeArray<byte> d;
    NativeArray<byte> e;
    NativeArray<byte> f;
    NativeArray<byte> g;
    NativeArray<byte> h;
    NativeArray<byte> i;
    NativeArray<byte> j;
    NativeArray<byte> k;
    NativeArray<byte> l;
    NativeArray<byte> m;
    NativeArray<byte> n;
    NativeArray<byte> o;
    NativeArray<byte> p;
    NativeArray<byte> q;
    NativeArray<byte> r;
    NativeArray<byte> s;
    NativeArray<byte> t;
    NativeArray<byte> u;
    NativeArray<byte> v;
    NativeArray<byte> w;
    NativeArray<byte> x;
    NativeArray<byte> y;
    NativeArray<byte> z;
    NativeArray<byte> aa;
    NativeArray<byte> ab;
    NativeArray<byte> ac;
    NativeArray<byte> ad;
    NativeArray<byte> ae;
    NativeArray<byte> af;
    NativeArray<byte> ag;
    NativeArray<byte> ah;
    NativeArray<byte> ai;
    NativeArray<byte> aj;
    NativeArray<byte> ak;
    NativeArray<byte> al;
    NativeArray<byte> am;
    NativeArray<byte> an;
    NativeArray<byte> ao;
    NativeArray<byte> ap;
    NativeArray<byte> aq;
    NativeArray<byte> ar;
    NativeArray<byte> @as;
    NativeArray<byte> at;
    NativeArray<byte> au;
    NativeArray<byte> av;
    NativeArray<byte> aw;
    NativeArray<byte> ax;
    NativeArray<byte> ay;
    NativeArray<byte> az;
    NativeArray<byte> ba;
    NativeArray<byte> bb;
    NativeArray<byte> bc;
    NativeArray<byte> bd;
    NativeArray<byte> be;
    NativeArray<byte> bf;
    NativeArray<byte> bg;
    NativeArray<byte> bh;
    NativeArray<byte> bi;
    NativeArray<byte> bj;
    NativeArray<byte> bk;
    NativeArray<byte> bl;
    NativeArray<byte> bm;
    NativeArray<byte> bn;
    NativeArray<byte> bo;
    NativeArray<byte> bp;
    NativeArray<byte> bq;
    NativeArray<byte> br;
    NativeArray<byte> bs;
    NativeArray<byte> bt;
    NativeArray<byte> bu;
    NativeArray<byte> bv;
    NativeArray<byte> bw;
    NativeArray<byte> bx;
    NativeArray<byte> by;
    NativeArray<byte> bz;
    NativeArray<byte> ca;
    NativeArray<byte> cb;
    NativeArray<byte> cc;
    NativeArray<byte> cd;
    NativeArray<byte> ce;
    NativeArray<byte> cf;
    NativeArray<byte> cg;
    NativeArray<byte> ch;
    NativeArray<byte> ci;
    NativeArray<byte> cj;
    NativeArray<byte> ck;
    NativeArray<byte> cl;
    NativeArray<byte> cm;
    NativeArray<byte> cn;
    NativeArray<byte> co;
    NativeArray<byte> cp;
    NativeArray<byte> cq;
    NativeArray<byte> cr;
    NativeArray<byte> cs;
    NativeArray<byte> ct;
    NativeArray<byte> cu;
    NativeArray<byte> cv;
    NativeArray<byte> cw;
    NativeArray<byte> cx;
    NativeArray<byte> cy;
    NativeArray<byte> cz;
    NativeArray<byte> da;
    NativeArray<byte> db;
    NativeArray<byte> dc;
    NativeArray<byte> dd;
    NativeArray<byte> de;
    NativeArray<byte> df;
    NativeArray<byte> dg;
    NativeArray<byte> dh;
    NativeArray<byte> di;
    NativeArray<byte> dj;
    NativeArray<byte> dk;
    NativeArray<byte> dl;
    NativeArray<byte> dm;
    NativeArray<byte> dn;
    NativeArray<byte> doo;
    NativeArray<byte> dp;
    NativeArray<byte> dq;
    NativeArray<byte> dr;
    NativeArray<byte> ds;
    NativeArray<byte> dt;
    NativeArray<byte> du;
    NativeArray<byte> dv;
    NativeArray<byte> dw;
    NativeArray<byte> dx;
    NativeArray<byte> dy;
    NativeArray<byte> dz;
    NativeArray<byte> ea;
    NativeArray<byte> eb;
    NativeArray<byte> ec;
    NativeArray<byte> ed;
    NativeArray<byte> ee;
    NativeArray<byte> ef;
    NativeArray<byte> eg;
    NativeArray<byte> eh;
    NativeArray<byte> ei;
    NativeArray<byte> ej;
    NativeArray<byte> ek;
    NativeArray<byte> el;
    NativeArray<byte> em;
    NativeArray<byte> en;
    NativeArray<byte> eo;
    NativeArray<byte> ep;
    NativeArray<byte> eq;
    NativeArray<byte> er;
    NativeArray<byte> es;
    NativeArray<byte> et;
    NativeArray<byte> eu;
    NativeArray<byte> ev;
    NativeArray<byte> ew;
    NativeArray<byte> ex;
    NativeArray<byte> ey;
    NativeArray<byte> ez;
    NativeArray<byte> fa;
    NativeArray<byte> fb;
    NativeArray<byte> fc;
    NativeArray<byte> fd;
    NativeArray<byte> fe;
    NativeArray<byte> ff;
    NativeArray<byte> fg;
    NativeArray<byte> fh;
    NativeArray<byte> fi;
    NativeArray<byte> fj;
    NativeArray<byte> fk;
    NativeArray<byte> fl;
    NativeArray<byte> fm;
    NativeArray<byte> fn;
    NativeArray<byte> fo;
    NativeArray<byte> fp;
    NativeArray<byte> fq;
    NativeArray<byte> fr;
    NativeArray<byte> fs;
    NativeArray<byte> ft;
    NativeArray<byte> fu;
    NativeArray<byte> fv;
    NativeArray<byte> fw;
    NativeArray<byte> fx;
    NativeArray<byte> fy;
    NativeArray<byte> fz;
    NativeArray<byte> ga;
    NativeArray<byte> gb;
    NativeArray<byte> gc;
    NativeArray<byte> gd;
    NativeArray<byte> ge;
    NativeArray<byte> gf;
    NativeArray<byte> gg;
    NativeArray<byte> gh;
    NativeArray<byte> gi;
    NativeArray<byte> gj;
    NativeArray<byte> gk;
    NativeArray<byte> gl;

    Stopwatch stopwatch = new Stopwatch();

    void Start() {
        a = NewArray();
        b = NewArray();
        c = NewArray();
        d = NewArray();
        e = NewArray();
        f = NewArray();
        g = NewArray();
        h = NewArray();
        i = NewArray();
        j = NewArray();
        k = NewArray();
        l = NewArray();
        m = NewArray();
        n = NewArray();
        o = NewArray();
        p = NewArray();
        q = NewArray();
        r = NewArray();
        s = NewArray();
        t = NewArray();
        u = NewArray();
        v = NewArray();
        w = NewArray();
        x = NewArray();
        y = NewArray();
        z = NewArray();
        aa = NewArray();
        ab = NewArray();
        ac = NewArray();
        ad = NewArray();
        ae = NewArray();
        af = NewArray();
        ag = NewArray();
        ah = NewArray();
        ai = NewArray();
        aj = NewArray();
        ak = NewArray();
        al = NewArray();
        am = NewArray();
        an = NewArray();
        ao = NewArray();
        ap = NewArray();
        aq = NewArray();
        ar = NewArray();
        @as = NewArray();
        at = NewArray();
        au = NewArray();
        av = NewArray();
        aw = NewArray();
        ax = NewArray();
        ay = NewArray();
        az = NewArray();
        ba = NewArray();
        bb = NewArray();
        bc = NewArray();
        bd = NewArray();
        be = NewArray();
        bf = NewArray();
        bg = NewArray();
        bh = NewArray();
        bi = NewArray();
        bj = NewArray();
        bk = NewArray();
        bl = NewArray();
        bm = NewArray();
        bn = NewArray();
        bo = NewArray();
        bp = NewArray();
        bq = NewArray();
        br = NewArray();
        bs = NewArray();
        bt = NewArray();
        bu = NewArray();
        bv = NewArray();
        bw = NewArray();
        bx = NewArray();
        by = NewArray();
        bz = NewArray();
        ca = NewArray();
        cb = NewArray();
        cc = NewArray();
        cd = NewArray();
        ce = NewArray();
        cf = NewArray();
        cg = NewArray();
        ch = NewArray();
        ci = NewArray();
        cj = NewArray();
        ck = NewArray();
        cl = NewArray();
        cm = NewArray();
        cn = NewArray();
        co = NewArray();
        cp = NewArray();
        cq = NewArray();
        cr = NewArray();
        cs = NewArray();
        ct = NewArray();
        cu = NewArray();
        cv = NewArray();
        cw = NewArray();
        cx = NewArray();
        cy = NewArray();
        cz = NewArray();
        da = NewArray();
        db = NewArray();
        dc = NewArray();
        dd = NewArray();
        de = NewArray();
        df = NewArray();
        dg = NewArray();
        dh = NewArray();
        di = NewArray();
        dj = NewArray();
        dk = NewArray();
        dl = NewArray();
        dm = NewArray();
        dn = NewArray();
        doo = NewArray();
        dp = NewArray();
        dq = NewArray();
        dr = NewArray();
        ds = NewArray();
        dt = NewArray();
        du = NewArray();
        dv = NewArray();
        dw = NewArray();
        dx = NewArray();
        dy = NewArray();
        dz = NewArray();
        ea = NewArray();
        eb = NewArray();
        ec = NewArray();
        ed = NewArray();
        ee = NewArray();
        ef = NewArray();
        eg = NewArray();
        eh = NewArray();
        ei = NewArray();
        ej = NewArray();
        ek = NewArray();
        el = NewArray();
        em = NewArray();
        en = NewArray();
        eo = NewArray();
        ep = NewArray();
        eq = NewArray();
        er = NewArray();
        es = NewArray();
        et = NewArray();
        eu = NewArray();
        ev = NewArray();
        ew = NewArray();
        ex = NewArray();
        ey = NewArray();
        ez = NewArray();
        fa = NewArray();
        fb = NewArray();
        fc = NewArray();
        fd = NewArray();
        fe = NewArray();
        ff = NewArray();
        fg = NewArray();
        fh = NewArray();
        fi = NewArray();
        fj = NewArray();
        fk = NewArray();
        fl = NewArray();
        fm = NewArray();
        fn = NewArray();
        fo = NewArray();
        fp = NewArray();
        fq = NewArray();
        fr = NewArray();
        fs = NewArray();
        ft = NewArray();
        fu = NewArray();
        fv = NewArray();
        fw = NewArray();
        fx = NewArray();
        fy = NewArray();
        fz = NewArray();
        ga = NewArray();
        gb = NewArray();
        gc = NewArray();
        gd = NewArray();
        ge = NewArray();
        gf = NewArray();
        gg = NewArray();
        gh = NewArray();
        gi = NewArray();
        gj = NewArray();
        gk = NewArray();
        gl = NewArray();
        System.Random random = new System.Random(12345);
        // Randomize the FSM states.
        for (int i = 0; i < entityCount; i++)
            a[i] = (byte)State.A;
    }

    NativeArray<byte> NewArray() {
        return new NativeArray<byte>(
            entityCount,
            Allocator.Persistent);
    }

    void Update() {
        stopwatch.Restart();
        for (int ii = 0; ii < entityCount; ii++) {
            switch ((State)a[ii]) {
                case State.A:
                    b[ii]++;
                    co[ii]++;
                    gl[ii]++;
                    break;
                case State.B:
                    d[ii]++;
                    bq[ii]++;
                    ee[ii]++;
                    break;
                case State.C:
                    g[ii]++;
                    bs[ii]++;
                    eg[ii]++;
                    break;
                case State.D:
                    j[ii]++;
                    bu[ii]++;
                    ej[ii]++;
                    break;
                case State.E:
                    m[ii]++;
                    bw[ii]++;
                    el[ii]++;
                    break;
                case State.F:
                    p[ii]++;
                    by[ii]++;
                    en[ii]++;
                    break;
                case State.G:
                    s[ii]++;
                    ca[ii]++;
                    ep[ii]++;
                    break;
                case State.H:
                    v[ii]++;
                    cc[ii]++;
                    er[ii]++;
                    break;
                case State.I:
                    y[ii]++;
                    ce[ii]++;
                    et[ii]++;
                    break;
                case State.J:
                    ab[ii]++;
                    cg[ii]++;
                    ev[ii]++;
                    break;
                case State.K:
                    ad[ii]++;
                    ci[ii]++;
                    ex[ii]++;
                    break;
                case State.L:
                    ag[ii]++;
                    ck[ii]++;
                    ez[ii]++;
                    break;
                case State.M:
                    aj[ii]++;
                    cm[ii]++;
                    fb[ii]++;
                    break;
                case State.N:
                    al[ii]++;
                    co[ii]++;
                    fd[ii]++;
                    break;
                case State.O:
                    ao[ii]++;
                    cq[ii]++;
                    ff[ii]++;
                    break;
                case State.P:
                    ar[ii]++;
                    cs[ii]++;
                    fh[ii]++;
                    break;
                case State.Q:
                    at[ii]++;
                    cu[ii]++;
                    fj[ii]++;
                    break;
                case State.R:
                    aw[ii]++;
                    cw[ii]++;
                    fl[ii]++;
                    break;
                case State.S:
                    az[ii]++;
                    cy[ii]++;
                    fn[ii]++;
                    break;
                case State.T:
                    bb[ii]++;
                    da[ii]++;
                    fp[ii]++;
                    break;
                case State.U:
                    be[ii]++;
                    dc[ii]++;
                    fr[ii]++;
                    break;
                case State.V:
                    bg[ii]++;
                    de[ii]++;
                    ft[ii]++;
                    break;
                case State.W:
                    bj[ii]++;
                    dg[ii]++;
                    fv[ii]++;
                    break;
                case State.X:
                    bl[ii]++;
                    di[ii]++;
                    fx[ii]++;
                    break;
                case State.Y:
                    bn[ii]++;
                    dk[ii]++;
                    fz[ii]++;
                    break;
                case State.Z:
                    bq[ii]++;
                    dm[ii]++;
                    gl[ii]++;
                    break;
            }
        }
        stopwatch.Stop();
        UnityEngine.Debug.Log($"SoA Update: {stopwatch.Elapsed.TotalMilliseconds:F4} ms");
    }

    void OnDestroy() {
        Dispose(ref a);
        Dispose(ref b);
        Dispose(ref c);
        Dispose(ref d);
        Dispose(ref e);
        Dispose(ref f);
        Dispose(ref g);
        Dispose(ref h);
        Dispose(ref i);
        Dispose(ref j);
        Dispose(ref k);
        Dispose(ref l);
        Dispose(ref m);
        Dispose(ref n);
        Dispose(ref o);
        Dispose(ref p);
        Dispose(ref q);
        Dispose(ref r);
        Dispose(ref s);
        Dispose(ref t);
        Dispose(ref u);
        Dispose(ref v);
        Dispose(ref w);
        Dispose(ref x);
        Dispose(ref y);
        Dispose(ref z);
        Dispose(ref aa);
        Dispose(ref ab);
        Dispose(ref ac);
        Dispose(ref ad);
        Dispose(ref ae);
        Dispose(ref af);
        Dispose(ref ag);
        Dispose(ref ah);
        Dispose(ref ai);
        Dispose(ref aj);
        Dispose(ref ak);
        Dispose(ref al);
        Dispose(ref am);
        Dispose(ref an);
        Dispose(ref ao);
        Dispose(ref ap);
        Dispose(ref aq);
        Dispose(ref ar);
        Dispose(ref @as);
        Dispose(ref at);
        Dispose(ref au);
        Dispose(ref av);
        Dispose(ref aw);
        Dispose(ref ax);
        Dispose(ref ay);
        Dispose(ref az);
        Dispose(ref ba);
        Dispose(ref bb);
        Dispose(ref bc);
        Dispose(ref bd);
        Dispose(ref be);
        Dispose(ref bf);
        Dispose(ref bg);
        Dispose(ref bh);
        Dispose(ref bi);
        Dispose(ref bj);
        Dispose(ref bk);
        Dispose(ref bl);
        Dispose(ref bm);
        Dispose(ref bn);
        Dispose(ref bo);
        Dispose(ref bp);
        Dispose(ref bq);
        Dispose(ref br);
        Dispose(ref bs);
        Dispose(ref bt);
        Dispose(ref bu);
        Dispose(ref bv);
        Dispose(ref bw);
        Dispose(ref bx);
        Dispose(ref by);
        Dispose(ref bz);
        Dispose(ref ca);
        Dispose(ref cb);
        Dispose(ref cc);
        Dispose(ref cd);
        Dispose(ref ce);
        Dispose(ref cf);
        Dispose(ref cg);
        Dispose(ref ch);
        Dispose(ref ci);
        Dispose(ref cj);
        Dispose(ref ck);
        Dispose(ref cl);
        Dispose(ref cm);
        Dispose(ref cn);
        Dispose(ref co);
        Dispose(ref cp);
        Dispose(ref cq);
        Dispose(ref cr);
        Dispose(ref cs);
        Dispose(ref ct);
        Dispose(ref cu);
        Dispose(ref cv);
        Dispose(ref cw);
        Dispose(ref cx);
        Dispose(ref cy);
        Dispose(ref cz);
        Dispose(ref da);
        Dispose(ref db);
        Dispose(ref dc);
        Dispose(ref dd);
        Dispose(ref de);
        Dispose(ref df);
        Dispose(ref dg);
        Dispose(ref dh);
        Dispose(ref di);
        Dispose(ref dj);
        Dispose(ref dk);
        Dispose(ref dl);
        Dispose(ref dm);
        Dispose(ref dn);
        Dispose(ref doo);
        Dispose(ref dp);
        Dispose(ref dq);
        Dispose(ref dr);
        Dispose(ref ds);
        Dispose(ref dt);
        Dispose(ref du);
        Dispose(ref dv);
        Dispose(ref dw);
        Dispose(ref dx);
        Dispose(ref dy);
        Dispose(ref dz);
        Dispose(ref ea);
        Dispose(ref eb);
        Dispose(ref ec);
        Dispose(ref ed);
        Dispose(ref ee);
        Dispose(ref ef);
        Dispose(ref eg);
        Dispose(ref eh);
        Dispose(ref ei);
        Dispose(ref ej);
        Dispose(ref ek);
        Dispose(ref el);
        Dispose(ref em);
        Dispose(ref en);
        Dispose(ref eo);
        Dispose(ref ep);
        Dispose(ref eq);
        Dispose(ref er);
        Dispose(ref es);
        Dispose(ref et);
        Dispose(ref eu);
        Dispose(ref ev);
        Dispose(ref ew);
        Dispose(ref ex);
        Dispose(ref ey);
        Dispose(ref ez);
        Dispose(ref fa);
        Dispose(ref fb);
        Dispose(ref fc);
        Dispose(ref fd);
        Dispose(ref fe);
        Dispose(ref ff);
        Dispose(ref fg);
        Dispose(ref fh);
        Dispose(ref fi);
        Dispose(ref fj);
        Dispose(ref fk);
        Dispose(ref fl);
        Dispose(ref fm);
        Dispose(ref fn);
        Dispose(ref fo);
        Dispose(ref fp);
        Dispose(ref fq);
        Dispose(ref fr);
        Dispose(ref fs);
        Dispose(ref ft);
        Dispose(ref fu);
        Dispose(ref fv);
        Dispose(ref fw);
        Dispose(ref fx);
        Dispose(ref fy);
        Dispose(ref fz);
        Dispose(ref ga);
        Dispose(ref gb);
        Dispose(ref gc);
        Dispose(ref gd);
        Dispose(ref ge);
        Dispose(ref gf);
        Dispose(ref gg);
        Dispose(ref gh);
        Dispose(ref gi);
        Dispose(ref gj);
        Dispose(ref gk);
        Dispose(ref gl);
    }

    static void Dispose(ref NativeArray<byte> array) {
        if (array.IsCreated)
            array.Dispose();
    }
}
