using System.Diagnostics;
using UnityEngine;

/// <summary>
/// Use managed arrays instead of native arrays.
/// </summary>
public class SoATest4 : MonoBehaviour {
    const int entityCount = 50_000;

    enum State : byte {
        A, B, C, D, E, F, G, H, I, J, K, L, M,
        N, O, P, Q, R, S, T, U, V, W, X, Y, Z
    }

    byte[] a;
    int[] b;
    int[] c;
    int[] d;
    int[] e;
    int[] f;
    int[] g;
    int[] h;
    int[] i;
    int[] j;
    int[] k;
    int[] l;
    int[] m;
    int[] n;
    int[] o;
    int[] p;
    int[] q;
    int[] r;
    int[] s;
    int[] t;
    int[] u;
    int[] v;
    int[] w;
    int[] x;
    int[] y;
    int[] z;
    int[] aa;
    int[] ab;
    int[] ac;
    int[] ad;
    int[] ae;
    int[] af;
    int[] ag;
    int[] ah;
    int[] ai;
    int[] aj;
    int[] ak;
    int[] al;
    int[] am;
    int[] an;
    int[] ao;
    int[] ap;
    int[] aq;
    int[] ar;
    int[] @as;
    int[] at;
    int[] au;
    int[] av;
    int[] aw;
    int[] ax;
    int[] ay;
    int[] az;
    int[] ba;
    int[] bb;
    int[] bc;
    int[] bd;
    int[] be;
    int[] bf;
    int[] bg;
    int[] bh;
    int[] bi;
    int[] bj;
    int[] bk;
    int[] bl;
    int[] bm;
    int[] bn;
    int[] bo;
    int[] bp;
    int[] bq;
    int[] br;
    int[] bs;
    int[] bt;
    int[] bu;
    int[] bv;
    int[] bw;
    int[] bx;
    int[] by;
    int[] bz;
    int[] ca;
    int[] cb;
    int[] cc;
    int[] cd;
    int[] ce;
    int[] cf;
    int[] cg;
    int[] ch;
    int[] ci;
    int[] cj;
    int[] ck;
    int[] cl;
    int[] cm;
    int[] cn;
    int[] co;
    int[] cp;
    int[] cq;
    int[] cr;
    int[] cs;
    int[] ct;
    int[] cu;
    int[] cv;
    int[] cw;
    int[] cx;
    int[] cy;
    int[] cz;
    int[] da;
    int[] db;
    int[] dc;
    int[] dd;
    int[] de;
    int[] df;
    int[] dg;
    int[] dh;
    int[] di;
    int[] dj;
    int[] dk;
    int[] dl;
    int[] dm;
    int[] dn;
    int[] doo;
    int[] dp;
    int[] dq;
    int[] dr;
    int[] ds;
    int[] dt;
    int[] du;
    int[] dv;
    int[] dw;
    int[] dx;
    int[] dy;
    int[] dz;
    int[] ea;
    int[] eb;
    int[] ec;
    int[] ed;
    int[] ee;
    int[] ef;
    int[] eg;
    int[] eh;
    int[] ei;
    int[] ej;
    int[] ek;
    int[] el;
    int[] em;
    int[] en;
    int[] eo;
    int[] ep;
    int[] eq;
    int[] er;
    int[] es;
    int[] et;
    int[] eu;
    int[] ev;
    int[] ew;
    int[] ex;
    int[] ey;
    int[] ez;
    int[] fa;
    int[] fb;
    int[] fc;
    int[] fd;
    int[] fe;
    int[] ff;
    int[] fg;
    int[] fh;
    int[] fi;
    int[] fj;
    int[] fk;
    int[] fl;
    int[] fm;
    int[] fn;
    int[] fo;
    int[] fp;
    int[] fq;
    int[] fr;
    int[] fs;
    int[] ft;
    int[] fu;
    int[] fv;
    int[] fw;
    int[] fx;
    int[] fy;
    int[] fz;
    int[] ga;
    int[] gb;
    int[] gc;
    int[] gd;
    int[] ge;
    int[] gf;
    int[] gg;
    int[] gh;
    int[] gi;
    int[] gj;
    int[] gk;
    int[] gl;

    Stopwatch stopwatch = new Stopwatch();

    void Start() {
        a = new byte[entityCount];
        b = NewArray();
        c = NewArray();
        d = NewArray();
        e = NewArray();
        f = NewArray();
        g = NewArray();
        h = NewArray();
        i = NewArray();
        j = NewArray();
        k = NewArray();
        l = NewArray();
        m = NewArray();
        n = NewArray();
        o = NewArray();
        p = NewArray();
        q = NewArray();
        r = NewArray();
        s = NewArray();
        t = NewArray();
        u = NewArray();
        v = NewArray();
        w = NewArray();
        x = NewArray();
        y = NewArray();
        z = NewArray();
        aa = NewArray();
        ab = NewArray();
        ac = NewArray();
        ad = NewArray();
        ae = NewArray();
        af = NewArray();
        ag = NewArray();
        ah = NewArray();
        ai = NewArray();
        aj = NewArray();
        ak = NewArray();
        al = NewArray();
        am = NewArray();
        an = NewArray();
        ao = NewArray();
        ap = NewArray();
        aq = NewArray();
        ar = NewArray();
        @as = NewArray();
        at = NewArray();
        au = NewArray();
        av = NewArray();
        aw = NewArray();
        ax = NewArray();
        ay = NewArray();
        az = NewArray();
        ba = NewArray();
        bb = NewArray();
        bc = NewArray();
        bd = NewArray();
        be = NewArray();
        bf = NewArray();
        bg = NewArray();
        bh = NewArray();
        bi = NewArray();
        bj = NewArray();
        bk = NewArray();
        bl = NewArray();
        bm = NewArray();
        bn = NewArray();
        bo = NewArray();
        bp = NewArray();
        bq = NewArray();
        br = NewArray();
        bs = NewArray();
        bt = NewArray();
        bu = NewArray();
        bv = NewArray();
        bw = NewArray();
        bx = NewArray();
        by = NewArray();
        bz = NewArray();
        ca = NewArray();
        cb = NewArray();
        cc = NewArray();
        cd = NewArray();
        ce = NewArray();
        cf = NewArray();
        cg = NewArray();
        ch = NewArray();
        ci = NewArray();
        cj = NewArray();
        ck = NewArray();
        cl = NewArray();
        cm = NewArray();
        cn = NewArray();
        co = NewArray();
        cp = NewArray();
        cq = NewArray();
        cr = NewArray();
        cs = NewArray();
        ct = NewArray();
        cu = NewArray();
        cv = NewArray();
        cw = NewArray();
        cx = NewArray();
        cy = NewArray();
        cz = NewArray();
        da = NewArray();
        db = NewArray();
        dc = NewArray();
        dd = NewArray();
        de = NewArray();
        df = NewArray();
        dg = NewArray();
        dh = NewArray();
        di = NewArray();
        dj = NewArray();
        dk = NewArray();
        dl = NewArray();
        dm = NewArray();
        dn = NewArray();
        doo = NewArray();
        dp = NewArray();
        dq = NewArray();
        dr = NewArray();
        ds = NewArray();
        dt = NewArray();
        du = NewArray();
        dv = NewArray();
        dw = NewArray();
        dx = NewArray();
        dy = NewArray();
        dz = NewArray();
        ea = NewArray();
        eb = NewArray();
        ec = NewArray();
        ed = NewArray();
        ee = NewArray();
        ef = NewArray();
        eg = NewArray();
        eh = NewArray();
        ei = NewArray();
        ej = NewArray();
        ek = NewArray();
        el = NewArray();
        em = NewArray();
        en = NewArray();
        eo = NewArray();
        ep = NewArray();
        eq = NewArray();
        er = NewArray();
        es = NewArray();
        et = NewArray();
        eu = NewArray();
        ev = NewArray();
        ew = NewArray();
        ex = NewArray();
        ey = NewArray();
        ez = NewArray();
        fa = NewArray();
        fb = NewArray();
        fc = NewArray();
        fd = NewArray();
        fe = NewArray();
        ff = NewArray();
        fg = NewArray();
        fh = NewArray();
        fi = NewArray();
        fj = NewArray();
        fk = NewArray();
        fl = NewArray();
        fm = NewArray();
        fn = NewArray();
        fo = NewArray();
        fp = NewArray();
        fq = NewArray();
        fr = NewArray();
        fs = NewArray();
        ft = NewArray();
        fu = NewArray();
        fv = NewArray();
        fw = NewArray();
        fx = NewArray();
        fy = NewArray();
        fz = NewArray();
        ga = NewArray();
        gb = NewArray();
        gc = NewArray();
        gd = NewArray();
        ge = NewArray();
        gf = NewArray();
        gg = NewArray();
        gh = NewArray();
        gi = NewArray();
        gj = NewArray();
        gk = NewArray();
        gl = NewArray();
        for (int i = 0; i < entityCount; i++)
            a[i] = (byte)State.A;
    }

    int[] NewArray() {
        return new int[entityCount];
    }

    void Update() {
        stopwatch.Restart();
        for (int ii = 0; ii < entityCount; ii++) {
            switch ((State)a[ii]) {
                case State.A:
                    b[ii]++;
                    co[ii]++;
                    gl[ii]++;
                    break;
                case State.B:
                    d[ii]++;
                    bq[ii]++;
                    ee[ii]++;
                    break;
                case State.C:
                    g[ii]++;
                    bs[ii]++;
                    eg[ii]++;
                    break;
                case State.D:
                    j[ii]++;
                    bu[ii]++;
                    ej[ii]++;
                    break;
                case State.E:
                    m[ii]++;
                    bw[ii]++;
                    el[ii]++;
                    break;
                case State.F:
                    p[ii]++;
                    by[ii]++;
                    en[ii]++;
                    break;
                case State.G:
                    s[ii]++;
                    ca[ii]++;
                    ep[ii]++;
                    break;
                case State.H:
                    v[ii]++;
                    cc[ii]++;
                    er[ii]++;
                    break;
                case State.I:
                    y[ii]++;
                    ce[ii]++;
                    et[ii]++;
                    break;
                case State.J:
                    ab[ii]++;
                    cg[ii]++;
                    ev[ii]++;
                    break;
                case State.K:
                    ad[ii]++;
                    ci[ii]++;
                    ex[ii]++;
                    break;
                case State.L:
                    ag[ii]++;
                    ck[ii]++;
                    ez[ii]++;
                    break;
                case State.M:
                    aj[ii]++;
                    cm[ii]++;
                    fb[ii]++;
                    break;
                case State.N:
                    al[ii]++;
                    co[ii]++;
                    fd[ii]++;
                    break;
                case State.O:
                    ao[ii]++;
                    cq[ii]++;
                    ff[ii]++;
                    break;
                case State.P:
                    ar[ii]++;
                    cs[ii]++;
                    fh[ii]++;
                    break;
                case State.Q:
                    at[ii]++;
                    cu[ii]++;
                    fj[ii]++;
                    break;
                case State.R:
                    aw[ii]++;
                    cw[ii]++;
                    fl[ii]++;
                    break;
                case State.S:
                    az[ii]++;
                    cy[ii]++;
                    fn[ii]++;
                    break;
                case State.T:
                    bb[ii]++;
                    da[ii]++;
                    fp[ii]++;
                    break;
                case State.U:
                    be[ii]++;
                    dc[ii]++;
                    fr[ii]++;
                    break;
                case State.V:
                    bg[ii]++;
                    de[ii]++;
                    ft[ii]++;
                    break;
                case State.W:
                    bj[ii]++;
                    dg[ii]++;
                    fv[ii]++;
                    break;
                case State.X:
                    bl[ii]++;
                    di[ii]++;
                    fx[ii]++;
                    break;
                case State.Y:
                    bn[ii]++;
                    dk[ii]++;
                    fz[ii]++;
                    break;
                case State.Z:
                    bq[ii]++;
                    dm[ii]++;
                    gl[ii]++;
                    break;
            }
        }
        stopwatch.Stop();
        UnityEngine.Debug.Log($"SoA Update: {stopwatch.Elapsed.TotalMilliseconds:F4} ms");
    }
}