#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class EditorUtils {
    public static void GenerateCatalog(List<GameObject> items, string catalogPath) {
        HandItemCatalog catalog =
            AssetDatabase.LoadAssetAtPath<HandItemCatalog>(
                catalogPath
            );
        if (catalog == null) {
            string directory =
                Path.GetDirectoryName(catalogPath);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);
            catalog = ScriptableObject.CreateInstance<HandItemCatalog>();
            AssetDatabase.CreateAsset(
                catalog,
                catalogPath
            );
        }
        catalog.SetItems(items);
        EditorUtility.SetDirty(catalog);
    }

    public static void GenerateEnum(List<GameObject> items, string enumName, string enumPath) {
        string directory = Path.GetDirectoryName(enumPath);
        // TODO: Maybe just log error and return if dir doesn't exist?
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);
        StringBuilder sb = new();
        sb.AppendLine($"// AUTO-GENERATED BY {nameof(HandItemGenerator)}. DO NOT EDIT!!!");
        sb.AppendLine();
        // TODO: Byte might not be enough for this. Consider changing.
        sb.AppendLine($"public enum {enumName} : byte {{");
        for (int i = 0; i < items.Count; i++) {
            sb.Append("    ");
            sb.Append(items[i].name);
            sb.Append(" = ");
            sb.Append(i);
            sb.AppendLine(",");
        }
        sb.AppendLine("}");
        File.WriteAllText(enumPath, sb.ToString());
    }

    public static bool IsCSharpKeyword(string value) {
        switch (value) {
            case "abstract":
            case "as":
            case "base":
            case "bool":
            case "break":
            case "byte":
            case "case":
            case "catch":
            case "char":
            case "checked":
            case "class":
            case "const":
            case "continue":
            case "decimal":
            case "default":
            case "delegate":
            case "do":
            case "double":
            case "else":
            case "enum":
            case "event":
            case "explicit":
            case "extern":
            case "false":
            case "finally":
            case "fixed":
            case "float":
            case "for":
            case "foreach":
            case "goto":
            case "if":
            case "implicit":
            case "in":
            case "int":
            case "interface":
            case "internal":
            case "is":
            case "lock":
            case "long":
            case "namespace":
            case "new":
            case "null":
            case "object":
            case "operator":
            case "out":
            case "override":
            case "params":
            case "private":
            case "protected":
            case "public":
            case "readonly":
            case "ref":
            case "return":
            case "sbyte":
            case "sealed":
            case "short":
            case "sizeof":
            case "stackalloc":
            case "static":
            case "string":
            case "struct":
            case "switch":
            case "this":
            case "throw":
            case "true":
            case "try":
            case "typeof":
            case "uint":
            case "ulong":
            case "unchecked":
            case "unsafe":
            case "ushort":
            case "using":
            case "virtual":
            case "void":
            case "volatile":
            case "while":
            case "add":
            case "alias":
            case "ascending":
            case "async":
            case "await":
            case "by":
            case "descending":
            case "dynamic":
            case "equals":
            case "from":
            case "get":
            case "global":
            case "group":
            case "into":
            case "join":
            case "let":
            case "nameof":
            case "on":
            case "orderby":
            case "partial":
            case "remove":
            case "select":
            case "set":
            case "unmanaged":
            case "value":
            case "var":
            case "when":
            case "where":
            case "yield":
                return true;
            default:
                return false;
        };
    }

    public static bool IsValidIdentifier(string id) {
        if (string.IsNullOrEmpty(id))
            return false;
        if (!char.IsLetter(id[0]) && id[0] != '_')
            return false;
        for (int i = 1; i < id.Length; i++) {
            if (!char.IsLetterOrDigit(id[i]) && id[i] != '_')
                return false;
        }
        if (IsCSharpKeyword(id))
            return false;
        return true;
    }

    public static bool Validate(List<GameObject> items) {
        HashSet<string> ids = new();
        foreach (GameObject item in items) {
            if (string.IsNullOrWhiteSpace(item.name)) {
                Debug.LogError($"Hand item '{item.name}' has an empty ID.", item);
                return false;
            }
            if (!IsValidIdentifier(item.name)) {
                Debug.LogError(
                    $"Hand item '{item.name}' has invalid ID '{item.name}'. IDs must be valid C# identifiers.",
                    item
                );
                return false;
            }
            if (!ids.Add(item.name)) {
                Debug.LogError($"Duplicate HandItem ID: '{item.name}'.");
                return false;
            }
        }
        return true;
    }
}
#endif
